---
driver:
  name: proxy
  host: 127.0.0.1
  reset_command: "exit 0"
  port: 55985
  username: vagrant
  password: vagrant

provisioner:
  name: dsc

transport:
  name: winrm

verifier:
  name: pester
  test_folder: Tests/Integration

platforms:
  - name: win-2012-r2-wmf5
    driver:
      box: nana-win-2012-r2-wmf51-1
    provisioner:
      dsc_local_configuration_manager_version: wmf5

suites:
  - name: default
    
